# Site settings
title: The Purpose
owner: neoelemento.com
email: publishing@neoelemento.com
description: > # this means to ignore newlines until "baseurl:"
  The Story
baseurl: "/the-purpose" # the subpath of your site, e.g. /blog/
url: "http://neoelemento.com" # the base hostname & protocol for your site
twitter_username: neoelemento
github_username:  neoelemento
next_episode: Nov 04, 2016

# Build settings
markdown: kramdown
sass:
    style: compressed
gems:
  - jemoji
  - jekyll-paginate

permalink: /:year/:month/:day/:title/
future: true
paginate: 10